### ISSUE TITLE
About experiment

### ISSUE THREAD

**Issue by YueDai0514** [IvanXie416/CMIGNet#1]
Hi，I have some questions about the experiment of  paper "Gaussian Noise with Lower Overlap. Finally, in order to test the performance of our method in a low overlap ratio, we placed the far point for the source point cloud and target point cloud independently", what is the Concrete values of "Lower Overlap" and how to implement the way of placing the far point for the source point cloud and target point cloud independently

**Comment by IvanXie416** [comment]
Thank you for your attention. For the concrete values of ‘Lower Overlap’ you can refer to [FIRE-Net](https://ieeexplore.ieee.org/document/9710761). It's very simple to implement, you just need to uncomment this [line](https://github.com/IvanXie416/CMIGNet/blob/981b2723527b38e87eec96a6ee41eedd25a750f2/data.py#L87).
